### ISSUE TITLE
The second REPL where !! conceptis being taught didn't work correctly.

### ISSUE THREAD

**Issue by itchkimel** [learn-co-curriculum/phase-0-pac-1-logical-operators#1]

**Comment by lizbur10** [comment]
Hi @itchkimel ! Thanks for spotting this issue and providing feedback! The instructions here and in an earlier lesson have been updated to reflect the new process for accessing and editing the REPL's. Note that the changes may not appear in Canvas right away.

Thanks for contributing to the Flatiron School curriculum! 💙
