### ISSUE TITLE
Return value not shown to student when executing repl.it's

### ISSUE THREAD

**Issue by karsonkalt** [learn-co-curriculum/phase-0-pac-1-logical-operators#3]
### Canvas Link

https://learning.flatironschool.com/courses/5274/pages/logical-operators?module_item_id=349309

### Concern

The return values in both repl.it's need to be wrapped in a console log to show students the return value when the repl executes.

<img width="785" alt="Screen Shot 2022-01-27 at 9 55 33 AM" src="https://user-images.githubusercontent.com/15637664/151384102-293fa111-1db5-401a-9898-c6d49149a211.png">

**Comment by lizbur10** [comment]
Hey @karsonkalt ! Thanks for bringing this to our attention! It looks like the behavior of repl.it changed recently, which is a little strange. We're working on a solution. In the meantime, students can type or copy/paste the code directly into the console window of the repl and just ignore the code window.

I will update this issue once it's resolved.

Thanks again! 💙

**Comment by karsonkalt** [comment]
Thanks @lizbur10, I saw their node execution change this week. Appreciated! 🙏

**Comment by lizbur10** [comment]
Hi again @karsonkalt! The updates to the prework lessons and labs that use replit have been completed. Note that, depending on when students were assigned to a prework course, the changes may or may not be reflected in their Canvas lessons. In other words, you may continue to see. some students having issues with this. 💙
